OnlineStore.UI/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using OnlineStore.Domain.Model;

namespace OnlineStore.UI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

OnlineStore.UI/Models/PageInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineStore.UI.Models
{
    public class PageInfo
    {
        public int totalItems { get; set; }
        public int itemsPerPage { get; set; }
        public int currentPage { get; set; }
        public int totalPages
        {
            get
            {
                return (int)Math.Ceiling((decimal)totalItems / itemsPerPage);
            }
        }
    }
}

OnlineStore.UI/Models/ProductList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using OnlineStore.Domain.Model;

namespace OnlineStore.UI.Models
{
    public class ProductList
    {
        public IEnumerable<Product> Products { get; set; }
        public PageInfo pageInfo { get; set; }
        public string currentCategory { get; set; }
    }
}

OnlineStore.UI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineStore.Domain.Model;
using OnlineStore.Domain.View;
using OnlineStore.UI.Models;

namespace OnlineStore.UI.Controllers
{
    public class CartController : Controller
    {
        private IProduct repository;
        private IOrderProcessor orderProcessor;
        public CartController(IProduct repo,IOrderProcessor proc)
        {
            repository = repo;
            orderProcessor = proc;
        }
        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel { Cart = cart, ReturnUrl = returnUrl });
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
        public RedirectToRouteResult AddToCart(Cart cart, int productId,string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);
            if(product!=null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);
            if(product!=null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

OnlineStore.UI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineStore.Domain.View;

namespace OnlineStore.UI.Controllers
{
    public class NavController : Controller
    {
        private IProduct repository;
        public NavController(IProduct repo)
        {
            repository = repo;
        }
        public PartialViewResult Menu(string category=null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

OnlineStore.UI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineStore.Domain.View;
using OnlineStore.UI.Models;

namespace OnlineStore.UI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProduct repository;
        public int pageSize = 4;
        public ProductController(IProduct repos)
        {
            repository = repos;
        }
        public ViewResult List(string category, int page=1)
        {
            ProductList model = new ProductList
            {
                Products = repository.Products
                .Where(p => category == null || p.Category==category)
                .OrderBy(p => p.ProductId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),
                pageInfo = new PageInfo
                {
                    currentPage = page,
                    itemsPerPage = pageSize,
                    totalItems = category==null ?repository.Products.Count() 
                    :repository.Products.Where(p=>p.Category==category).Count()
                },
                currentCategory=category
            };
            return View(model);
        }
    }
}

OnlineStore.UI/Views/Cart/Checkout.cshtml
@model OnlineStore.Domain.Model.ShippingDetails
@{
    ViewBag.Title = "Online Shopping Store: Checkout";
}
<h2>Check out now</h2>
<p>Please enter your details, and we'll ship your goods right away!</p>
@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <h3>Ship to</h3>
    <div class="form-group">
        <label>Name:</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    </div>
    <h3>Address</h3>
    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName != "Name" && property.PropertyName !=
            "GiftWrap")
        {
            <div class="form-group">
                <label>
                    @(property.DisplayName ?? property.PropertyName)
            </label>
            @Html.TextBox(property.PropertyName, null, new
          {
              @class = "form-control"
          })
        </div>
        }
    }
    <h3>Options</h3>
    <div class="checkbox">
        <label>
            @Html.EditorFor(x => x.GiftWrap)
            Gift wrap these items
        </label>
    </div>
    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Complete order" />
    </div>
}

OnlineStore.UI/Views/Cart/Index.cshtml
@model OnlineStore.UI.Models.CartIndexViewModel

<style>
    #cartTable td {
        vertical-align: middle;
    }
</style>
@{
    ViewBag.Title = "Online Store: Your Cart";
}
<h2>Your cart</h2>
<table id="cartTable" class="table">
    <thead>
        <tr>
            <th>Quantity</th>
            <th>Item</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Products.Name</td>
                <td class="text-right">
                    @line.Products.Price.ToString("c")
                </td>
                <td class="text-right">
                    @((line.Quantity * line.Products.Price).ToString("c"))
                </td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("ProductId", line.Products.ProductId)
                        @Html.HiddenFor(x => x.ReturnUrl)
                        <input class="btn btn-sm btn-warning"
                               type="submit" value="Remove" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue shopping</a>
    @Html.ActionLink("Checkout now", "Checkout", null,
   new { @class = "btn btn-primary" })
</div>

OnlineStore.UI/Views/Cart/Summary.cshtml
@model OnlineStore.Domain.Model.Cart

<div class="navbar-right">
    @Html.ActionLink("Checkout", "Index", "Cart",
   new { returnUrl = Request.Url.PathAndQuery },
   new { @class = "btn btn-default navbar-btn" })
</div>
<div class="navbar-text navbar-right">
    <b>Your cart:</b>
    @Model.Lines.Sum(x => x.Quantity) item(s),
    @Model.ComputeTotalValue().ToString("c")
</div>

OnlineStore.UI/Views/Nav/Menu.cshtml
@model  IEnumerable<string>

@Html.ActionLink("ALL","List","Product",null,
    new { @class="btn btn-block btn-default btn-lg"})

@foreach(var link in Model)
{
    @Html.RouteLink(link, new
{
    controller="Product",
    action="List",
    category=link,
    page=1
},
    new { @class="btn btn-block btn-default btn-lg"
    +(link==ViewBag.SelectedCategory? " btn-primary":"")
    }
    )
}

OnlineStore.UI/Views/Product/List.cshtml
@model OnlineStore.UI.Models.ProductList

@{
    ViewBag.Title = "Products";
}

@foreach(var mod in Model.Products)
{
   @Html.Partial("ProductSummary", mod)
}
<div class="btn-group pull-right">
    @Html.PageLinks(Model.pageInfo, x=> Url.Action("List",new { page = x ,category=Model.currentCategory}))
</div>

OnlineStore.UI/Views/Shared/ProductSummary.cshtml
@model OnlineStore.Domain.Model.Product

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label-default"> @Model.Price.ToString("c")</span>
    </h3>
    @using (Html.BeginForm("AddToCart","Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ProductId)
            @Html.Hidden("returnUrl",Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to cart" />
        </div>
    }
    <span class="lead">@Model.Description</span>
</div>

OnlineStore.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Online Store</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">Online Store</a>
        @Html.Action("Summary","Cart")
    </div>
    <div class="row panel">
        <div id="categories" class="col-lg-3">
            @Html.Action("Menu","Nav")  
        </div>
        <div class="col-lg-7">@RenderBody()</div>
    </div>
</body>
</html>